# Regression
Lets see aome code samples from the sklearn example codes, which can be found [here](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html).

We inport numpy and Linear Regression model from sklearn.linear_model module. We initialize a simple list of datapoints as a numpy array, create another array which implements the simple linear equation $y = 1 * x_0 + 5 * x_1 + 4$.

We fit the model with input and output and calculate the score.

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]], dtype = np.int64)
# y = 1 * x_0 + 5 * x_1 + 4
y = np.dot(X, np.array([1, 5], dtype=np.int64)) + 4
reg = LinearRegression().fit(X, y)
reg.score(X, y)

1.0

We see the coefficients of this regression.

In [2]:
reg.coef_

array([1., 5.])

We see the y-axis intercept.

In [3]:
reg.intercept_ 

4.000000000000002

Now we predict what will be the value of y for the corresponding value v given as a list of single point.

In [4]:
v = np.array([[3, 5]], dtype=np.int64)
v

array([[3, 5]], dtype=int64)

In [5]:
reg.predict(v)

array([32.])